### ISSUE TITLE
How to increase the 'totalCarCounter' in app/config.py?

### ISSUE THREAD

**Issue by ConnLiu** [iliasger/TRAPP#1]
Your project is really awesome! And I want to use it to do something.
But here I have some problems:
1. How to increase the 'totalCarCounter' in app/config.py?
I find that it maybe related to the file, /app/entity/CarHistory.py, but how should I generate the item in CarHistory.py, such as 
```
'car-99': {'balanced': 0.05592876377678914,
               'max_speed': 0.06216045630598542,
               'min_length': 0.06521429586421325},
```
2. BTW, what is the meaning of the three elements of the cars? (balanced, max_speed, min_length)

Thanks in advance!

**Comment by iliasger** [comment]
Hi Conn, 
happy that you are interested in using this project. 
1. Indeed, you should change the totalCarCounter variable at /app/entity/CarHistory.py. To generate the CarHistory.py that corresponds to the new number of cars, check points 5 and 6 at https://github.com/iliasger/TRAPP/blob/experiments/Beta_Alpha_Testing_README.md.
BTW, if you also want to also use a different map than the default one (CrowdNav) chewck points 3 and 4 as well. Also, you can use one of the maps of Manhattan, Boulder, Annapolis, Duluth, or Iowa city found under the /app/map folder in the experiments branch: https://github.com/iliasger/TRAPP/tree/experiments/app/map
2. Each of (balanced, max_speed, min_length) corresponds to a different type of router: max_speed routes cars based on the maximum speeds allowed on the streets only (selecting the ones that maximize the overall maximum speed of a route), min_length based on the length of the streets (selecting a route of minimum distance), and balanced is a linear combination of the above.

You can also read more in these two papers: 
- http://wwwbroy.in.tum.de/~gerostat/pubs/SEAMS19-EPOS-SUMO.pdf
- https://arxiv.org/abs/2001.03384

Good luck and let me know if I can help further. 

Ilias

**Comment by ConnLiu** [comment]
Thanks very much~ Your answer is really helpful.
